/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl_thmang;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author NO NAME
 */
public class Taikhoan extends javax.swing.JFrame {

    /**
     * Creates new form Taikhoan
     */
    public Taikhoan() {
        initComponents();
    }
    String hoten;
    public Taikhoan(String hoten) {
        initComponents();
        this.hoten = hoten;
        lbhoten.setText(hoten);
        hienthi();
    }
    
    String sua = "Sửa";
    String luu = "Lưu";
    private void hienthi(){
        txthoten.setText(hoten);
         try {
            Connection c = ketnoi.KN();
            Statement stm = c.createStatement();
            ResultSet rs = stm.executeQuery("SELECT MaNV FROM nhanvien where TenNV = '"+hoten+"'");
            while (rs.next()) {
                txtmanv.setText(rs.getString("MaNV"));
            }
            c.close();
        } catch (SQLException ex) {
           Logger.getLogger(qlyuudai.class.getName()).log(Level.SEVERE, null, ex);
        }
           try {
            Connection c = ketnoi.KN();
            Statement stm = c.createStatement();
            ResultSet rs1 = stm.executeQuery("SELECT Sdt FROM nhanvien where TenNV = '"+hoten+"'");
            while (rs1.next()) {
                txtsdt.setText(rs1.getString("Sdt"));
            }
            c.close();
        } catch (SQLException ex) {
           Logger.getLogger(qlyuudai.class.getName()).log(Level.SEVERE, null, ex);
        }
            try {
            Connection c = ketnoi.KN();
            Statement stm = c.createStatement();
            ResultSet rs2 = stm.executeQuery("SELECT DiaChi FROM nhanvien where TenNV = '"+hoten+"'");
            while (rs2.next()) {
                txtdc.setText(rs2.getString("DiaChi"));
            }
            c.close();
        } catch (SQLException ex) {
           Logger.getLogger(qlyuudai.class.getName()).log(Level.SEVERE, null, ex);
        }
             try {
            Connection c = ketnoi.KN();
            Statement stm = c.createStatement();
            ResultSet rs3 = stm.executeQuery("SELECT Email FROM nhanvien where TenNV = '"+hoten+"'");
            while (rs3.next()) {
                txtemail.setText(rs3.getString("Email"));
            }
            c.close();
        } catch (SQLException ex) {
           Logger.getLogger(qlyuudai.class.getName()).log(Level.SEVERE, null, ex);
        }
              try {
            Connection c = ketnoi.KN();
            Statement stm = c.createStatement();
            ResultSet rs4 = stm.executeQuery("SELECT ChucVu FROM nhanvien where TenNV = '"+hoten+"'");
            while (rs4.next()) {
                txtchucvu.setText(rs4.getString("ChucVu"));
            }
            c.close();
        } catch (SQLException ex) {
           Logger.getLogger(qlyuudai.class.getName()).log(Level.SEVERE, null, ex);
        }
               try {
            Connection c = ketnoi.KN();
            Statement stm = c.createStatement();
            ResultSet rs5 = stm.executeQuery("SELECT MatKhau FROM nhanvien where TenNV = '"+hoten+"'");
            while (rs5.next()) {
                txtmatkhau.setText(rs5.getString("MatKhau"));
            }
            c.close();
        } catch (SQLException ex) {
           Logger.getLogger(qlyuudai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtmanv = new javax.swing.JTextField();
        txthoten = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        txtdc = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtchucvu = new javax.swing.JTextField();
        txtmatkhau = new javax.swing.JTextField();
        btn6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lbhoten = new javax.swing.JLabel();
        lbtrangchu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Thông tin cá nhân");

        jLabel2.setText("Mã NV");

        jLabel3.setText("Họ Tên");

        jLabel5.setText("Địa Chỉ");

        jLabel6.setText("Email");

        jLabel7.setText("Chức Vụ");

        jLabel8.setText("Mật Khẩu");

        txtmanv.setEnabled(false);

        txthoten.setEnabled(false);

        txtsdt.setEnabled(false);

        txtdc.setEnabled(false);

        txtemail.setEnabled(false);

        txtchucvu.setEnabled(false);

        txtmatkhau.setEnabled(false);

        btn6.setText("Sửa");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        jLabel9.setText("SỐ ĐT");

        btn5.setText("Sửa");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn4.setText("Sửa");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn3.setText("Sửa");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn2.setText("Sửa");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn1.setText("Sửa");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btnthoat.setText("Thoát ");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl_thmang/img/370162895_259407543790261_3839074197647649421_n.png"))); // NOI18N

        lbhoten.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbhoten.setText("jLabel11");

        lbtrangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl_thmang/img/399969071_698403348889309_1184252070341447807_n.png"))); // NOI18N
        lbtrangchu.setText("jLabel11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lbtrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtmanv)
                    .addComponent(btnthoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txthoten)
                    .addComponent(txtsdt)
                    .addComponent(txtdc)
                    .addComponent(txtemail)
                    .addComponent(txtchucvu)
                    .addComponent(txtmatkhau)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn6)
                            .addComponent(btn5)
                            .addComponent(btn4)
                            .addComponent(btn3))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(lbhoten, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(12, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbtrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(btn2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbhoten)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6))
                .addGap(41, 41, 41)
                .addComponent(btnthoat)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
                Login ad = new Login();
                this.setVisible(false);
                ad.setVisible(true);
    }//GEN-LAST:event_btnthoatActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
            String manv = txtmanv.getText();
            String tennv = txthoten.getText();
        if(btn1.getText() == sua){
            txthoten.setEnabled(true);
            btn1.setText(luu);
            }
        else{
            try {
                // TODO add your handling code here:
                Connection kn = ketnoi.KN();
                Statement stm = kn.createStatement();
                stm.executeUpdate("update nhanvien set TenNV ='"+tennv+"' where MaNV = '"+manv+"' ");
                ResultSet rs = stm.executeQuery("select TenNV from nhanvien where MaNV = '"+manv+"'");
                while(rs.next()){
                    txthoten.setText(rs.getString("TenNV"));
                    }
                kn.close();
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Taikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
             JOptionPane.showMessageDialog(Taikhoan.this, "Sửa thành công", "", JOptionPane.INFORMATION_MESSAGE);
            btn1.setText(sua);
            txthoten.setEnabled(false);
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
            String sdt = txtsdt.getText();
            String manv = txtmanv.getText();
        if(btn2.getText() == sua){
            txtsdt.setEnabled(true);
            btn2.setText(luu);
            }
         else{
            try {
                // TODO add your handling code here:
                Connection kn = ketnoi.KN();
                Statement stm = kn.createStatement();
                stm.executeUpdate("update nhanvien set Sdt ='"+sdt+"' where MaNV = '"+manv+"' ");
                ResultSet rs = stm.executeQuery("select Sdt from nhanvien where MaNV = '"+manv+"'");
                while(rs.next()){
                    txtsdt.setText(rs.getString("Sdt"));
                    }
                kn.close();
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Taikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(Taikhoan.this, "Sửa thành công", "", JOptionPane.INFORMATION_MESSAGE);
            btn2.setText(sua);
            txtsdt.setEnabled(false);
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
            String dc = txtdc.getText();
            String manv = txtmanv.getText();
        if(btn3.getText() == sua){
            txtdc.setEnabled(true);
            btn3.setText(luu);
            }
        else{
            try {
                // TODO add your handling code here:
                Connection kn = ketnoi.KN();
                Statement stm = kn.createStatement();
                stm.executeUpdate("update nhanvien set DiaChi ='"+dc+"' where MaNV = '"+manv+"' ");
                ResultSet rs = stm.executeQuery("select DiaChi from nhanvien where MaNV = '"+manv+"'");
                while(rs.next()){
                    txtdc.setText(rs.getString("DiaChi"));
                    }
                kn.close();
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Taikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(Taikhoan.this, "Sửa thành công", "", JOptionPane.INFORMATION_MESSAGE);
            btn3.setText(sua);
            txtdc.setEnabled(false);
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
            String email = txtemail.getText();
            String manv = txtmanv.getText();
        if(btn4.getText() == sua){
            txtemail.setEnabled(true);
            btn4.setText(luu);
            }
        else{
            try {
                // TODO add your handling code here:
                Connection kn = ketnoi.KN();
                Statement stm = kn.createStatement();
                stm.executeUpdate("update nhanvien set Email ='"+email+"' where MaNV = '"+manv+"' ");
                ResultSet rs = stm.executeQuery("select Email from nhanvien where MaNV = '"+manv+"'");
                while(rs.next()){
                    txtemail.setText(rs.getString("Email"));
                    }
                kn.close();
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Taikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(Taikhoan.this, "Sửa thành công", "", JOptionPane.INFORMATION_MESSAGE);
            btn4.setText(sua);
            txtemail.setEnabled(false);
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
            String cv = txtchucvu.getText();
            String manv = txtmanv.getText();
        if(btn5.getText() == sua){
            txtchucvu.setEnabled(true);
            btn5.setText(luu);
            }
        else{
            try {
                // TODO add your handling code here:
                Connection kn = ketnoi.KN();
                Statement stm = kn.createStatement();
                stm.executeUpdate("update nhanvien set ChucVu ='"+cv+"' where MaNV = '"+manv+"' ");
                ResultSet rs = stm.executeQuery("select ChucVu from nhanvien where MaNV = '"+manv+"'");
                while(rs.next()){
                    txtchucvu.setText(rs.getString("ChucVu"));
                    }
                kn.close();
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Taikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(Taikhoan.this, "Sửa thành công", "", JOptionPane.INFORMATION_MESSAGE);
            btn5.setText(sua);
            txtchucvu.setEnabled(false);
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
            String mk = txtmatkhau.getText();
            String manv = txtmanv.getText();
        if(btn6.getText() == sua){
            txtmatkhau.setEnabled(true);
            btn6.setText(luu);
            }
        else{
            try {
                // TODO add your handling code here:
                Connection kn = ketnoi.KN();
                Statement stm = kn.createStatement();
                stm.executeUpdate("update nhanvien set MatKhau ='"+mk+"' where MaNV = '"+manv+"' ");
                ResultSet rs = stm.executeQuery("select MatKhau from nhanvien where MaNV = '"+manv+"'");
                while(rs.next()){
                    txtmatkhau.setText(rs.getString("MatKhau"));
                    }
                kn.close();
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Taikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(Taikhoan.this, "Sửa thành công", "", JOptionPane.INFORMATION_MESSAGE);
            btn6.setText(sua);
            txtmatkhau.setEnabled(false);
        }
    }//GEN-LAST:event_btn6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Taikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Taikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Taikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Taikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Taikhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btnthoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbhoten;
    private javax.swing.JLabel lbtrangchu;
    private javax.swing.JTextField txtchucvu;
    private javax.swing.JTextField txtdc;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtmanv;
    private javax.swing.JTextField txtmatkhau;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables
}
